import type { DebateEvent, ModelOption, Outcome, RunOption, SnapshotManifest, WhitelistPair } from './types'

export const API_BASE = import.meta.env.VITE_API_BASE ?? 'http://localhost:8000'

// Static (Path A) mode: no backend. Reads run/outcome JSON bundled under
// public/data/ (generated by `bun run bundle`) and replays client-side. Unset
// ⇒ the normal API/SSE path (local dev, or Path B against a hosted backend).
export const STATIC = !!import.meta.env.VITE_STATIC
const asset = (p: string) => `${import.meta.env.BASE_URL}${p}`

interface IndexRun { run: string; model: string; recorded_at: string }
interface IndexPair { ticker: string; as_of: string; has_outcome: boolean; runs: IndexRun[] }

let indexCache: Promise<IndexPair[]> | null = null
function loadIndex(): Promise<IndexPair[]> {
  if (!indexCache) {
    indexCache = fetch(asset('data/index.json')).then((r) => {
      if (!r.ok) throw new Error(`index fetch failed: ${r.status}`)
      return r.json()
    })
  }
  return indexCache
}

/** Static replay: the recorded run's events, played client-side over the reducer. */
export async function loadRunEvents(run: string): Promise<DebateEvent[]> {
  const res = await fetch(asset(`data/runs/${run}`))
  if (!res.ok) throw new Error(`run fetch failed: ${res.status}`)
  return (await res.json()).events as DebateEvent[]
}

export interface StreamOpts {
  backend?: string // live: pin the LLM backend for this run
  model?: string // live: pin the model
  run?: string // replay: the specific recorded run to re-stream
}

export function streamUrl(ticker: string, asOf: string, replay: boolean, opts: StreamOpts = {}): string {
  const params = new URLSearchParams({ ticker, as_of: asOf })
  if (replay) {
    params.set('replay', '1')
    if (opts.run) params.set('run', opts.run)
  } else {
    if (opts.backend) params.set('backend', opts.backend)
    if (opts.model) params.set('model', opts.model)
  }
  return `${API_BASE}/stream?${params}`
}

export async function fetchModels(): Promise<ModelOption[]> {
  if (STATIC) return [] // no live runs without a backend
  const res = await fetch(`${API_BASE}/models`)
  if (!res.ok) throw new Error(`models fetch failed: ${res.status}`)
  return res.json()
}

export async function fetchRuns(ticker: string, asOf: string): Promise<RunOption[]> {
  if (STATIC) {
    const pair = (await loadIndex()).find((p) => p.ticker === ticker && p.as_of === asOf)
    return pair ? pair.runs : []
  }
  const res = await fetch(`${API_BASE}/runs?ticker=${ticker}&as_of=${asOf}`)
  if (!res.ok) throw new Error(`runs fetch failed: ${res.status}`)
  return res.json()
}

/** Build the point-in-time snapshot if missing (ADR 0006) — resolves once it is
 * on disk and leak-checked; an existing pair returns immediately. */
export async function ensureSnapshot(ticker: string, asOf: string): Promise<void> {
  const params = new URLSearchParams({ ticker, as_of: asOf })
  const res = await fetch(`${API_BASE}/snapshots?${params}`, { method: 'POST' })
  if (!res.ok) {
    const detail = await res.json().then((b) => b.detail, () => res.statusText)
    throw new Error(detail)
  }
}

export async function fetchWhitelist(): Promise<WhitelistPair[]> {
  if (STATIC) return (await loadIndex()).map(({ ticker, as_of }) => ({ ticker, as_of }))
  const res = await fetch(`${API_BASE}/whitelist`)
  if (!res.ok) throw new Error(`whitelist fetch failed: ${res.status}`)
  return res.json()
}

/** The exact point-in-time snapshot fed to the agents — for the Provenance
 *  manifest panel + per-citation cross-check. 404s when the pair isn't whitelisted. */
export async function fetchSnapshotManifest(ticker: string, asOf: string): Promise<SnapshotManifest> {
  const url = STATIC
    ? asset(`data/snapshots/${ticker}_${asOf}.json`)
    : `${API_BASE}/snapshot?ticker=${ticker}&as_of=${asOf}`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`snapshot fetch failed: ${res.status}`)
  return res.json()
}

/** Fetched only after the Verdict — the Outcome never rides the stream (ADR 0002). */
export async function fetchOutcome(ticker: string, asOf: string): Promise<Outcome> {
  const url = STATIC
    ? asset(`data/outcomes/${ticker}_${asOf}.json`)
    : `${API_BASE}/outcome?ticker=${ticker}&as_of=${asOf}`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`no outcome available (${res.status})`)
  return res.json()
}
